### ISSUE TITLE
Example with c++ module

### ISSUE THREAD

**Issue by gsabran** [airbnb/BuckSample#67]
Hi!

I've done a few tries to reference a c++ module directly from a swift module but I could not get it to work. I've seen that you've implemented an `apple_cxx_lib macro`. Would you have an example of how to use it with first party code?

**Comment by dfed** [comment]
Can you post what you tried in your `BUCK` file and what wasn't working about it? A PR against this repo as an example would be illustrative, and let us help you more efficiently.

For some background, they key for getting c++ working for us was having [this line](https://github.com/airbnb/BuckSample/blob/91e61e4c142c9c199e3101a97bcb7a2a039b402f/Config/buck_rule_macros.bzl#L221) in the `apple_lib` call.

You should be able to create a `first_party_cxx_library` that looks very, very similar to `first_party_library`, except instead of the call to `apple_lib` you could use `apple_cxx_lib`. Of course, it might be even better to add a `has_cxx` flag to `first_party_library`, and have it call through to `apple_cxx_lib` instead of `apple_lib`, but then we'd need to conditionally change what we look for in `sources` just like we did for [has_objective_c](https://github.com/airbnb/BuckSample/blob/91e61e4c142c9c199e3101a97bcb7a2a039b402f/Config/buck_rule_macros.bzl#L160).

We don't have any first-party C++ code, so to be entirely honest this isn't high on our to-do list. But we're happy to help you get something working, especially if you'll contribute back to this repo 🙂

**Comment by thedavidharris** [comment]
prebuilt_cxx_library has some weird quirks with module maps that have to be configured with Buck too, for what it’s worth.

We have a C/C++/Obj-C/Swift all in one library compiled together, but going right from C++ to Swift has never been easy even within Xcode

**Comment by dfed** [comment]
> We have a C/C++/Obj-C/Swift all in one library compiled together

😱❗️

That's not a bridge we've crossed! If you're interested in contributing a PR, we'd love to have an example module like that in the repo.

**Comment by bachand** [comment]
> We have a C/C++/Obj-C/Swift all in one library compiled together

Y’all are adventurous. I like it 😉

**Comment by thedavidharris** [comment]
Hah I mean I wouldn’t suggest it, it mostly wraps the C++ code in Objective C which then gets used in Swift parts. That isn’t so bad with umbrella headers.


Importing modules that are cross language tends to be where we’ve had issues.

**Comment by gsabran** [comment]
Not an expert, but it compiles and runs https://github.com/airbnb/BuckSample/pull/73

**Comment by dfed** [comment]
#73 is merged. Closing this issue out since I believe it is resolved. Thank you again for the help!
